### ISSUE TITLE
Import from AD does not work

### ISSUE THREAD

**Issue by KEHO4133** [zhunussovr/phonebook#2]
I have modified the phbook.py file and saved the information for the LDAP connection, but nothing is imported. Only existing information from the contactlist.json file is displayed.

**Comment by zhunussovr** [comment]
> I have modified the phbook.py file and saved the information for the LDAP connection, but nothing is imported. Only existing information from the contactlist.json file is displayed.

Hi, thanks for your comment.
Do you received any errors during execution phbook.py?

I’ll try to test it today’s evening and will respond you back with results.

**Comment by KEHO4133** [comment]
Hi, thanks for the quick response.
Very good work.

I didn't get any errors while running phbook.py?

**Comment by zhunussovr** [comment]
> 
> 
> Hi, thanks for the quick response.
> Very good work.
> 
> I didn't get any errors while running phbook.py?

Hi, I've tested today this python script under Ubuntu OS and it works normally. contactlist.json file was updated accordingly. The script was tested under my demo Active Directory domain with only few users inside, but it's totally enough. 
Configuration for my testing you can find under new branch which I created for this issue:
https://github.com/zhunussovr/phonebook/tree/issue01_demo_test

Just download it to your machine, correct the LDAP section, and try to run.

There are you also can find screenshot from my machine as a piece of evidence and updated the README file which may help you to run phbook.py properly. 

Running a web interface is out of the scope of this issue. Should you have any questions or comments just let me known.

**Comment by KEHO4133** [comment]
Hi, thanks for testing.
Sorry, I haven't shared all the information with you, but I'm using Windows Server 2016 and IIS.
Do you also have experience with Windows?

**Comment by zhunussovr** [comment]
> 
> 
> Hi, thanks for testing.
> Sorry, I haven't shared all the information with you, but I'm using Windows Server 2016 and IIS.
> Do you also have experience with Windows?

Hi, well I've not tested it under Windows machine, but I don't see any issue with that from my point of view. I can test it as well today.
